### ISSUE TITLE
Feature: As a developer I can set a global default version to use when none other is specified

### ISSUE THREAD

**Issue by 01dCod3r** [kadena-community/pactup#26]
I seems, as documented, that the ``default`` command does nothing more that create an alias named "default'. Is that true?

ASDF supports the notion of a global version which is the default, as well as local version specifications at the directory level.

When I use ``--version-file-strategy=recursive`` and cd outside of my project tree it fails to find a pact version. Every directory change produces this:
```
Can't find an installed Pact version matching pact-versions.
Do you want to install it? answer [y/N]: n
error: Requested version pact-versions is not currently installed
```

Setting ``default`` does not help:
``` 
% pactup default 4.11.0
% cd ..
Can't find an installed Pact version matching pact-versions.
Do you want to install it? answer [y/N]: n
error: Requested version pact-versions is not currently installed
```

It's not clear what it is offering to install. What version is "pact-versions"?

Expected and desired behavior: When the recursive strategy does not find a version specification, use ``default`` if it is defined.

If ``default`` is not defined I'm not sure what is best. I think that I would prefer that it silently do nothing. It is not clear what it is trying to install, or how it could even infer what should be installed.

As it is the recursive strategy is too annoying to be useful.

**Comment by salamaashoush** [comment]
@01dCod3r with version `0.2.16` if you have a default version it will be used if pactup failed to  infer pact version recessively in parent folders, if no default version is set we throw a helpful error message 
```
error: Could not find any version to use. Maybe you don't have a default version set?
Try running `pactup default <VERSION>` to set one,
or create a .pact-version file inside your project to declare a Pact version.
```
you can also just disable the feature if you don't want this new behavior, and btw thanks for the issue report indeed the old logic was buggy
